### ISSUE TITLE
Test application does not show anything on device.

### ISSUE THREAD

**Issue by stewe93** [saantiaguilera/android-api-SecureKeys#51]
### Description

As I see from the reversed apk, the test application should show the value for the "description" key in a text view on the MainActivity but it shows nothing.
First tested on emulator: I think its blocked from config,nothing shown, so working fine.
Second tested on stock Samsung Galaxy S7: App opens, nothing shown. (Android 7.0)
Third tested on stock Samsung Galaxy Note 4: App opens, nothing shown. (Android 6.0.1)
Fourth tested on stock LG L65: App opens, nothing shown. (Android 4.4.2)

### Reproduction

1, Download apk from wiki link.
2, Extract.
3, adb install testapp-release.apk.
4, Open application on device.
5, Nothing shown.

**Comment by saantiaguilera** [comment]
You should disable adb / debugger before using it. The application is for testing how easy/hard it is to achieve the values. If you could debug it or connect it to adb, there would be no point at all.

Im not mantaining this project too much since im short of time + the main issue is the android studio sync, which I havent yet figured out why it bypasses my apt / extraction

Cheers

**Comment by stewe93** [comment]
First of all thanks for your fast reply! 

I forget about the debug option check, my fault sorry! 
But:
right now tested on the same devices again plus on a OnePlus 3 and on a Pixel XL. All devices shows the "Some other key is hidden, what does it say?" when I turn off the USB debugging option except the Galaxy S7. 
After my tests (First I thought its android version related, Pixel is on 8.0 and OnePlus is on 7.1) I think it is something about samsung modifications in the android system. Unfortunately right now I dont have another S7 but I will try to "find" another one and test on it again. 
Until then I close this issue.

Bests
